services:
  db:
    image: postgres:15-alpine
    container_name: kikku-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kikku}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kikku}
      POSTGRES_DB: ${POSTGRES_DB:-kikku_local}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
